services:
  spenicle-e2e-postgres:
    image: postgres:16-alpine
    container_name: spenicle-e2e-postgres
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db_name

    volumes:
      - spenicle_e2e_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d db_name"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - spenicle_e2e

  spenicle-e2e-redis:
    image: redis:8.4.0-alpine
    container_name: spenicle-e2e-redis
    ports:
      - "6380:6379"
    networks:
      - spenicle_e2e

  spenicle-e2e-api:
    build:
      context: ../..
      dockerfile: deploy/Dockerfile
    container_name: spenicle-e2e-api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: spenicle-e2e-postgres
      DB_PORT: 5432
      DB_USER: db_user
      DB_PASSWORD: db_password
      DB_NAME: db_name
      APP_PORT: 8080
      WEB_PORT: 3000
      REDIS_URL: spenicle-e2e-redis:6379
      IS_DEV_ENV: false
      JWT_SECRET: random-text-to-just-need-to-be-filled-for-jwt-secret
      ADMIN_USERNAME: admin_username
      ADMIN_PASSWORD: admin_password
    depends_on:
      spenicle-e2e-postgres:
        condition: service_healthy
    networks:
      - spenicle_e2e

volumes:
  spenicle_e2e_postgres_data:

networks:
  spenicle_e2e:
    driver: bridge
