services:
  spenicle-backend-postgres:
    image: postgres:16-alpine
    container_name: spenicle-backend-postgres
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: spenicle-backend
    ports:
      - "5432:5432"
    volumes:
      - spenicle_backend_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d spenicle-backend"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - spenicle-backend

  spenicle-backend-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spenicle-backend-api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: spenicle-backend-postgres
      DB_PORT: 5432
      DB_USER: db_user
      DB_PASSWORD: db_password
      DB_NAME: spenicle-backend
      APP_PORT: "8080"
      JWT_SECRET: local-development-jwt-for-testing-purpose
      IS_DEV_ENV: true,
      ADMIN_USERNAME: my-username
      ADMIN_PASSWORD: my-password
    depends_on:
      spenicle-backend-postgres:
        condition: service_healthy
    networks:
      - spenicle-backend

volumes:
  spenicle_backend_postgres_data:

networks:
  spenicle-backend:
    driver: bridge
