services:
  spenicle-backend-postgres:
    image: postgres:16-alpine
    container_name: spenicle-backend-postgres
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: spenicle-backend
    ports:
      - "5432:5432"
    volumes:
      - spenicle_backend_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d spenicle-backend"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - spenicle-backend

  spenicle-backend-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: spenicle-backend-api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: spenicle-backend-postgres
      DB_PORT: 5432
      DB_USER: db_user
      DB_PASSWORD: db_password
      DB_NAME: spenicle-backend
      JWT_SECRET: local-development-jwt-for-testing-purpose
      ADMIN_USERNAME: my-username
      ADMIN_PASSWORD: my-password
      REDIS_URL: spenicle-backend-redis:6379
      SNAP_EXCHANGE_URL: http://spenicle-snap-exchange:8080
    volumes:
      - .:/app
    depends_on:
      spenicle-backend-postgres:
        condition: service_healthy
    networks:
      - spenicle-backend

  spenicle-backend-redis:
    image: redis:8.4.0-alpine
    container_name: spenicle-backend-redis
    ports:
      - "6379:6379"
    networks:
      - spenicle-backend

  spenicle-snap-exchange:
    build:
      context: ../backend-snap-exchange
      dockerfile: Dockerfile
    container_name: spenicle-snap-exchange
    ports:
      - "8081:8080"
    environment:
      APP_PORT: "8080"
      ECB_URL: https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml
      LOG_LEVEL: debug
    volumes:
      - ../backend-snap-exchange:/app
      - /app/tmp
    networks:
      - spenicle-backend

volumes:
  spenicle_backend_postgres_data:

networks:
  spenicle-backend:
    driver: bridge
