services:
  spenicle-build-postgres:
    image: postgres:16-alpine
    container_name: spenicle-build-postgres
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db_name
    ports:
      - "5432:5432"
    volumes:
      - spenicle_postgres_build_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d db_name"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - spenicle-build

  spenicle-build-api:
    build:
      context: ..
      dockerfile: scripts/Dockerfile
    container_name: spenicle-build-api
    ports:
      - "3000:3000"
    environment:
      DB_HOST: spenicle-build-postgres
      DB_PORT: 5432
      DB_USER: db_user
      DB_PASSWORD: db_password
      DB_NAME: db_name
      JWT_SECRET: long-text-to-just-filled-out-the-jwt-secret-variable
      ADMIN_USERNAME: admin_username
      ADMIN_PASSWORD: admin_password
    depends_on:
      spenicle-build-postgres:
        condition: service_healthy
    networks:
      - spenicle-build

volumes:
  spenicle_postgres_build_data:

networks:
  spenicle-build:
    driver: bridge
