name: Build and Publish Image

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-artifact: image-tar
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (single-arch linux/amd64) and save artifact
        run: |
          IMAGE_NAME=spenicle:build
          docker buildx build --platform linux/amd64 -f deploy/Dockerfile -t ${IMAGE_NAME} --load --build-arg WEB_APP_VERSION=${{ github.event.release.tag_name }} .
          docker save ${IMAGE_NAME} -o image.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-tar
          path: image.tar
          retention-days: 7

  push-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: image-tar

      - name: Log into GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Release Tag
        run: |
          docker load -i image.tar
          docker tag spenicle:build ghcr.io/${{ github.repository_owner }}/spenicle:${{ github.event.release.tag_name }}
          docker push ghcr.io/${{ github.repository_owner }}/spenicle:${{ github.event.release.tag_name }}

  push-latest:
    needs: build
    if: ${{ !github.event.release.prerelease }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: image-tar

      - name: Log into GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Latest Tag
        run: |
          docker load -i image.tar
          docker tag spenicle:build ghcr.io/${{ github.repository_owner }}/spenicle:latest
          docker push ghcr.io/${{ github.repository_owner }}/spenicle:latest
